services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "3000:3000"
    volumes:
      - ./queue.db:/app/queue.db
      - ./model.pkl:/app/model.pkl
      - ./forecast.json:/app/forecast.json

  frontend:
    build:
      context: ./frontend/queu-frontend
      dockerfile: Dockerfile.frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

  detection:
    build:
      context: ./queue-detection
      dockerfile: Dockerfile.detection
    ports:
      - "5050:5050"
    environment:
      - BACKEND_URL=http://backend:3000
    privileged: true
    volumes:
      - /run/udev:/run/udev:ro
    depends_on:
      - backend

